### ISSUE TITLE
Lights extension wont open(some HW extensions incompatible with RPi)

### ISSUE THREAD

**Issue by QuadDam** [Vegz78/McAirpos#12]
Hello again, when I use the light extension in Mkaecode to access the neopixels (as my students are downloading to Pygamer) when I download their elf file to pu on our larger arcade machine it gives me an error.  I remove the light extension and it disappears.  I am running retropi on my mini arcade with a raspi 3B+.   Maybe this is not solvable but just thought I would tell you about it.

**Comment by Vegz78** [comment]
Hi @QuadDam,

Might it be related to this?:
https://github.com/microsoft/pxt-arcade/issues/3045#issuecomment-773822437
https://github.com/Vegz78/McAirpos/issues/7#issuecomment-773947958

It seems that some of the extensions are compatible only with certain hardware, whereas the web simulator runs most of them, regardless of the hardware being compatible/connected or not.

I have seen some times that extensions are imported, but not used or important to the game project.
https://support.microbit.org/support/solutions/articles/19000089673-update-remove-an-extension-from-the-makecode-editor

**Comment by QuadDam** [comment]
Ah makes sense, would be great to have a block so we could access the gpio pins to play with some addressable lights, maybe in future updates, thanks for your help!

**Comment by Vegz78** [comment]
Only mention of GPIO for Raspberry I have ever seen is here:
https://forum.makecode.com/t/raspberry-pi-gpio-output

Not sure how hard or if it would be possible to use or modify any of the other hardware extensions, or make such an extension for the Raspberry Pi GPIOs yourself.

But would be great!

Maybe you could try to get @mmoskal's or @peli's etc. attention about a possible way in the above thread on the MakeCode Arcade forum?

**Comment by QuadDam** [comment]
Interesting, I do run the trinket M0 from the pi to control the lights but thats just power, could be controlled through serial I bet, thanks I will take a look!

**Comment by Vegz78** [comment]
Good luck! If you find a solution, it would be great to hear back from you here, or maybe better, on the MakeCode Arcade forum. I believe there are others interested, as well, and it would make MC Arcade on the Raspberry Pi much more interesting for a large pool of devices and users.
