### ISSUE TITLE
game crashed(type casting issue in game code)

### ISSUE THREAD

**Issue by felixtsu** [Vegz78/McAirpos#21]
// ---------- /tmp/McAirpos.log.  -----------------------------------------------

launCharc starting /home/pi/RetroPie/roms/makecode/arcade-AlphaFinalMyKnightIntegration.elf with automatic gamepad mappings...

Highest found input event number: 8
Gamepad search hits:
/home/pi/McAirpos/McAirpos/uinput-mapper/input-read -vp /dev/input/event7 2>&1 | grep -e BTN_START -e BTN_SOUTH -e BTN_PINKIE, Output:     BTN_START  → ([0, EV_KEY], BTN_START)
Keyboard search hit:
cat /proc/bus/input/devices | grep -B 5 -A 5 Handlers=sysrq | grep -B 7 -A 3 -e EV=12001 -e EV=10001 | grep -B 2 -A 8 -E 'Phys=(usb\S+\/input1:1|usb\S+\/input0|[a-zA-Z0-9]{2}(:[a-zA-Z0-9]{2}){5}.*)' | tr ' ' '\n' | grep event | head -1 | tr -d [:cntrl:], Output:event0

Found 1 gamepad to configure on:
/dev/input/event7

Found 1 keyboard to configure on:
/dev/input/event0

Starting UInput-Mapper with command:
(/home/pi/McAirpos/McAirpos/uinput-mapper/input-read -C -D /dev/input/event7 /dev/input/event7 /dev/input/event0 | sudo /home/pi/McAirpos/McAirpos/uinput-mapper/input-create -C -S /home/pi/McAirpos/McAirpos/uinput-mapper/configs/arcade1.py &)
Setting up UInputMapper in MakeCode Arcade game's /sd/arcade.cfg with:
SCAN_CODES=/dev/input/event2

[-317986404] GC block 16376b @ 0x20000000
[       0] runtime starting, pid=4007...
[       4] FB: vc4drmfb at 3840x2160 3840x2160 bpp=16
[       8] FB: vc4drmfb at 3840x2160 3840x2160 bpp=16 7680
[      12] init keys
[      12] read config: /sd/arcade.cfg 
[      19] SCAN_CODES=/dev/input/event2
[      23] BTN_LEFT=30
[      26] BTN_RIGHT=32
[      30] BTN_UP=17
[      34] BTN_DOWN=31
[      37] BTN_A=29
[      42] BTN_B=42
[      46] BTN_LEFT2=105
[      49] BTN_RIGHT2=106
[      52] BTN_UP2=103
[      56] BTN_DOWN2=108
[      59] BTN_A2=100
[      65] BTN_B2=57
[      68] BTN_RESET=59
[      71] BTN_EXIT=1
[      74] BTN_MENU=60
[      77] config done
[      81] sx=18 sy=18 ox=480 oy=0 32=0
[      86] fbuf=0xb5444000 sz:16588800
[     110] loop
[     334] GC block 16376b @ 0x20004000
[     341] GC block 16376b @ 0x20008000
[    1239] PCM name: 'default'
[    1245] PCM state: PREPARED
[   32294] failed type check for 0x20007138 @0x5bd89
[   32303] VT 0x7ec7c - objtype 4 classNo 23
[   32307] PANIC 984
[   32311] errno=0 Success

//----------------------------------------------------------------------

I have two games failing for the same reason

[   32294] failed type check for 0x20007138 @0x5bd89
[   32303] VT 0x7ec7c - objtype 4 classNo 23
[   32307] PANIC 984

**Comment by Vegz78** [comment]
Hi @felixtsu,

These «failed type check/panic» combinations I haven’t seen before.

Are you perhaps running RetroPie/the game inside an X-Windows session?

Are any of the standard demo games from makecode.com, like Jumpy Platformer or Falling Duck, working?

What happens if you exit to the basic Linux console and either:
1. `~/McAirpos/McAirpos/launCharc/launCharc ~/RetroPie/roms/makecode/gamefile.elf`
, or just:
2. `~/RetroPie/roms/makecode/gamefile.elf`
?

**Comment by felixtsu** [comment]
@Vegz78 After running the elf from command line, I've realized my game code has type casting issue, which works in browser not ELF. 
Thanks for your help. Cheers.

**Comment by Vegz78** [comment]
Thanks for closing the issue with feedback, @felixtsu!
