### ISSUE TITLE
Trying to rotate video of MakeCode game(not directly related to McAirpos)

### ISSUE THREAD

**Issue by vikramv786** [Vegz78/McAirpos#24]
I am using Raspberry Pi4 on an Arcade1Up Machine (Vertical screen). I have been unable to rotate the screen for the game.

Have tried following options but none of them work
1. Modified /boot/cmdline.txt and added a video parameter at the end of the line

video=HDMI-A-1:1920x1080M@60,rotate=90

2. Edited the autostart.sh script, in /opt/retropie/configs/all, and added

emulationstation --screenrotate 3

3.  Edited /opt/retropie/configs/all/retroarch.cfg and added

video_allow_rotate=yes
video_rotation = "3"

4. Created a custom cfg file with below contents called "makecode.cfg" and placed it in the roms/makecode folder that contains the elf game file. Gave it execute permissions

video_allow_rotate=yes
video_rotation = "3"

5  Edited /boot/config.txt and added 
display_rotate=3

Any suggestion to rotate my game?

**Comment by Vegz78** [comment]
I am sorry, @vikramv786, but I have no experience with rotating either a display or a MCA game on a RPi/Linux machine. I only know that the MCA games write directly to the framebuffer somehow and logs some [screen initialization routine during startup](https://github.com/microsoft/pxt-arcade/issues/3812), but I only stumbled upon the screen related [termfix](https://github.com/hobbitalastair/termfix) repo by chance while working on McAirpos and I don't know whether or how the screen could be configured with a game config file.

I would suggest trying the [MCA forum](https://forum.makecode.com/search?q=rotate%20%23share-your-arcade-projects-here), an [issue at the pxt-arcade github repo](https://github.com/microsoft/pxt-arcade/issues?q=is%3Aissue), or maybe the [Raspberry Pi forum](https://forums.raspberrypi.com/search.php?keywords=rotate&terms=all&author=&sc=1&sf=titleonly&sr=posts&sk=t&sd=d&st=0&ch=300&t=0&submit=Search) for help.

If you need any help configuring the controllers on the Arcade1Up, I might be of better use, and I can leave this issue open for a while here, as well, in case someone else might have a better clue.

**Comment by Vegz78** [comment]
This issue unfortunately doesn't seem to get any help here. Now closing, since it is more related to the RPi OS, RetroPie/Retroarch and/or MakeCode Arcade, than the McAirpos launcher itself. I hope you get the help your are seeking or figure it out!
