### ISSUE TITLE
Can't find game (file) in Retropie(<systemList> tag required at end of es_systems.cfg)

### ISSUE THREAD

**Issue by Maki2007** [Vegz78/McAirpos#25]
Hello
I have added my elf file to /home/pi/RetroPie/roms/makecode/. But when I go to RetroPie I cant find the Makecode Menu in RetroPie. When I somehow, I don't know, enter the menu in RetroPie, My game are not here.
I don't know whats going wrong.

**Comment by Vegz78** [comment]
Hi and thanks for your feedback and trying McAirpos!

Have you tried `sudo chmod -R 755 ~/RetroPie/roms/makecode` and then restarting EmulationStation?

**Comment by Maki2007** [comment]
Yes, I have tried that

**Comment by Vegz78** [comment]
Did you install McAirpos manually or with the installation script?

Since you can’t find the MakeCode menu nor the games inside RetroPie, I am thinking that you maybe are lacking the MakeCode entry inside /etc/emulationstation/es_systems.cfg?:
https://github.com/Vegz78/McAirpos/blob/master/McAirpos/EmulationStation/es_systems.cfg_MakeCode

**Comment by Maki2007** [comment]
Sorry
I copied the ./McAirpos/EmulationStation/es_systems.cfg_MakeCode file to the end, the \</systemList\> should be the last line

**Comment by Vegz78** [comment]
Yeah, \</systemList\> must be kept as the last concluding line when adding entries to the original _es\_systems.cfg_ file.

All good and working now, and we can close this issue?

**Comment by Maki2007** [comment]
Yes sure, I got my games from my Meowbit running on my pi. But I have an another issue. If I play games with the settings or database extension (Save data like text) I can’t play them.

**Comment by Vegz78** [comment]
Great!

In particular, the settings extension/namespace does not work 100% on the Raspberry Pi, but there is a functioning work-around:
https://github.com/Vegz78/McAirpos/issues/14#issuecomment-900680039
https://github.com/microsoft/pxt-arcade/issues/3812

In general, the saving to disk functions seem to need to be run a couple of times in a row per game to start to work ok, no idea why, and I have not tested if the same applies to booting with the official MakeCode image for Raspberry and uf2 files instead(should work in a similar fashion). It is the same executable .elf file inside the uf2 files, but the runtime environment inside MakeCode's boot image might be a little bit different from on regular Raspberry Pi OS.

There is also different extensions support for different hardware, etc.:
https://github.com/Vegz78/McAirpos/issues/12

But core Arcade functions seem to work ok most places.

If the settings workaround does not work for you, or you need more help, please open a new issue with the right topic. 

God luck and keep on retro game making and playing!
