### ISSUE TITLE
[Retroflag GPi Case + Zero W + Recalbox v8] Button mapping(detected&working)

### ISSUE THREAD

**Issue by Vegz78** [Vegz78/McAirpos#28]
Once again with the great and valuable help from @rdmueller during our work on upgrading uinput-mapper with Python 3.x support and getting MakeCode Arcade(MCA) games to run with McAirpos on Recalbox version 8.0, I am happy to announce that McAirpos has been tested successfully to work out of the box with button mappings for the Retroflag GPi case!

The only missing button is the MCA games' in-game menu button.

This missing button and possible future optimizations in a custom _arcade1.py_ script tailored for the GPi for best performance might be uploaded and announced here in the future.

Stay tuned and thank you very much, @rdmueller!!!

**Comment by Vegz78** [comment]
Closing this issue, since @rdmueller has confirmed that McAirpos works with the Retroflag GPi case/controller.

I am still curious about how he specifically reconfigured the missing in-game menu button, and hope that @rdmueller will elaborate here one day. ;-)

**Comment by rdmueller** [comment]
:-) just gave it a try - I haven't configured the special menu button. And I don't miss it, since IMHO it is mostly useless, at least for the GPi

**Comment by Vegz78** [comment]
Agreed! Thanks for the test and feedback, and hope you are doing well!
