### ISSUE TITLE
Typo in new install script(fixed in pull request)

### ISSUE THREAD

**Issue by rdmueller** [Vegz78/McAirpos#29]
"recalbos" instead of "recalbox"

PR is coming

**Comment by Vegz78** [comment]
Great and thanks again for testing, your feedback and for the pull request!

You hereby confirm that the installation scripts now work as intended, with a resulting working addition of MakeCode Games into Recalbox 8.0 and no new side effects, with these changes?:
https://github.com/Vegz78/McAirpos/pull/30

**Comment by rdmueller** [comment]
I tested the script (without HDMI fix) and it worked on my GPi case

**Comment by Vegz78** [comment]
Looks good and thanks also for confirming the positive results from your testing! ;-)
