### ISSUE TITLE
wrong size splash screen(fixed in pull request)

### ISSUE THREAD

**Issue by rdmueller** [Vegz78/McAirpos#32]
the new splash screen for the recalbox is cool. 
For smaller displays, it should be resized.
As @Vegz78 already pointed out, the splash screen is shown through a cli tool called `fbv2`

https://github.com/Vegz78/McAirpos/blob/master/McAirpos/launCharc/launCharc.c#L212

This tool as an option `-f` to resize the screen.

I did a quick test of the command line from the source on the remote shell and it seems to work.

PR already prepared.

**Comment by Vegz78** [comment]
Very nice that you found and tested with success on a smaller screen the fbv2 resize command line argument!
