### ISSUE TITLE
First button doesnt pick up(MakeCode Arcade/pxt-arcade issue)

### ISSUE THREAD

**Issue by cfpwastaken** [Vegz78/McAirpos#35]
The first time you press a button inside a game it doesnt pick it up. (Recalbox only issue?)

**Comment by Vegz78** [comment]
I know, but I am not sure about this one.

Is it the same when launching an MCA game alone without launCharc, and with /sd/arcade.cfg set to keyboard event number?

**Comment by Vegz78** [comment]
Just tested running two different MakeCode Arcade .elf game files without the launCharc launcher, and I also had to press twice any button/key the first time for the game to respond.

It has also been indicated before that this is a MakeCode Arcade/pxt-arcade issue:
https://github.com/Vegz78/McAirpos/issues/22#issuecomment-911254613

https://github.com/microsoft/pxt-arcade/issues
