### ISSUE TITLE
elf file flags for bigger files or alternative file format?(MakeCode/game programming issue)

### ISSUE THREAD

**Issue by yblacky** [Vegz78/McAirpos#66]
Hey,

is it possible to add a flag when creating .elf files so that larger projects can be compiled? Or is another file format possible?

I'm currently struggling with the fact that my Arcade MakeCode game is way too big, even if I delete a lot of functions/images I can't get below the maximum size.

LG

**Comment by Vegz78** [comment]
Hi @yblacky,

Did you find a solution/answers to your questions?

As the .elf compilations of MakeCode Arcade games both were made for the team's [original "handheld" solution for the one of the first Raspberry Pi Zeroes](https://learn.adafruit.com/makecode-arcade-with-raspberry-pi-zero/what-is-makecode-arcade) which has the same size restriction as for other devices AND the particular .elf compilation for ARM Linux isn't very actively maintained, there are some restrictions and unresolved errors on the games being able to run on ARM Linux compared to what can run on the web simulator and on more actively supported devices.

So in effect, there seems to be a subset of instructions and games being able to run on ARM Linux, but where the exact boundaries go are unknown to me. 

One example is the open issue at pxt-arcade here: https://github.com/microsoft/pxt-arcade/issues/4847
Another example is a resolved issue here: https://github.com/microsoft/pxt-arcade/issues/3812

In any case, this is a matter for the MakeCode Team which is virtually impossible for us on the outside to do anything about, unless you get closely acquainted with the pxt source code and suggest solutions/pull request to the MakeCode Team, as the second example proved possible.

Getting your game files smaller and other game code related issues is better food for all the game programming experts [forum.makecode.com](https://forum.makecode.com/c/share-your-arcade-projects-here/5)
